name: "Main CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: app_test
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_user_password
    env:
      RAILS_ENV: test
      RAILS_DB_HOST: localhost
      RAILS_DB_USER: ci_user
      RAILS_DB_PASSWORD: ci_user_password
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
